### ISSUE TITLE
Update all instances of mevn-cli within docs

### ISSUE THREAD

**Issue by jamesjose03** [madlabsinc/mevn-cli#76]
### Minor Documentation Fix
Replace all occurrences of `mevn-cli` with `mevn` 
Here is the file to work with:  [README.md](https://github.com/madlabsinc/mevn-cli/tree/master/docs/guide)

**Comment by kamerk22** [comment]
I can work on this issue.

**Comment by jamesjose03** [comment]
Sure, go ahead! 😀😀

**Comment by ajomadlabs** [comment]
Fixed #83

**Comment by kamerk22** [comment]
@ajomadlabs This issue is not fixed. `README.md` needs to be updated.
I'm on it

**Comment by kamerk22** [comment]
@ajomadlabs Fixed!
